import HomeIcon from "./home-icon.svg"
import ExploreIcon from "./hashtag-icon.svg"
import NotificationIcon from "./notification-icon.svg"
import MessagesIcon from "./message-icon.svg"
import BookmarkIcon from "./bookmark-icon.svg"
import ListIcon from "./list-icon.svg"
import ProfileIcon from "./profile-icon.svg"
import MoreIcon from "./more-icon.svg"
import DarkModeIcon from "./dark-mode-icon.svg"
import ChooseImgICon from "./img-choose-icon.svg"
import GifIcon from "./gif-icon.svg"
import StatsIcon from "./sats-icon.svg"
import SmileIcon from "./smile-icon.svg"
import ScheduleImg from "./schedule-icon.svg"
import AvatarIcon from "./avatar-icon.svg"
import DotsIcon from "./dots-icon.svg"
import Designinsta from "./designinsta.svg"
import Cloutexhibition from "./cloutexhibition.svg"
import CreativePhoto from "./creative-photo.svg"
import KebabImg from "./kebab-img.png"

export{HomeIcon,ExploreIcon,NotificationIcon,MessagesIcon,BookmarkIcon,ListIcon,ProfileIcon,MoreIcon,DarkModeIcon,ChooseImgICon,GifIcon,StatsIcon,SmileIcon,ScheduleImg,AvatarIcon,DotsIcon,Designinsta,Cloutexhibition,CreativePhoto,KebabImg}